// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nahreo-marks/ConvergingPaths.tsx": () => import("../components/mockups/nahreo-marks/ConvergingPaths.tsx"),
  "./components/mockups/nahreo-marks/OpenCompass.tsx": () => import("../components/mockups/nahreo-marks/OpenCompass.tsx"),
  "./components/mockups/nahreo-marks/SharedOrbit.tsx": () => import("../components/mockups/nahreo-marks/SharedOrbit.tsx")
};
